# Generated by Django 2.0.3 on 2021-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId', models.CharField(default=0, max_length=255)),
                ('payerAccountId', models.CharField(default=0, max_length=255)),
                ('billingPeriodStartDate', models.CharField(default=0, max_length=255)),
                ('billingPeriodEndDate', models.CharField(default=0, max_length=255)),
                ('usageAccountId', models.CharField(default=0, max_length=255)),
                ('usageStartDate', models.CharField(default=0, max_length=255)),
                ('usageEndDate', models.CharField(default=0, max_length=255)),
                ('productCode', models.CharField(default=0, max_length=255)),
                ('usageAmount', models.FloatField(default=0, max_length=20)),
                ('blendedRate', models.FloatField(default=0, max_length=20)),
                ('blendedCost', models.FloatField(default=0, max_length=20)),
            ],
        ),
    ]
